config/routes.rb
Rails.application.routes.draw do
  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

 resources :users
 resources :products

 root 'users#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  before_action :check_session

  def check_session
  	if session[:user_id].blank?
  		redirect_to login_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  	@product = Product.new
  end

  def create
  	@product=current_user.products.new(product_params)
  	if @product.save
  		flash[:success] ="New product added"
  		redirect_to action: :index
  	else
  		flash[:danger] ="All fields are mandatory"
  		render :new
  	end
  end

  def index
  	@product=current_user.products
  end

  def edit
  end

  def show
  end

  def product_params
  	params.require(:product).permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_action :check_session, :only =>[:new, :create, :log_in]
	
  def new
  end

  def create
  	user=User.find_by_email(params[:sessions][:email])
  	if user && user.authenticate(params[:sessions][:password])
  		flash[:success] = "Welcome"
  		log_in user
  		redirect_to user
  	else
  		flash.now[:danger] = "Check your details"
  		render :new
  	end
  end

  def destroy
  	log_out
  	flash[:danger] = "See you later"
  	redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_session, :only => [:new, :create]
  def new
  	@user =User.new
  end

  def create
  	@user =User.new(user_params)
  	if @user.save
  		redirect_to @user
      log_in @user
  	else
  		render :new
  	end
  end
 
  def index
    @user=User.where(email: current_user.email)
  	#@user=current_user
    
  end

  def edit
  	@user =User.find params[:id]
  end

  def update
  	@user =User.find params[:id]
  	if @user.update(user_params)
  		redirect_to @user
  	else
  		render :edit
  	end
  end

  def destroy
  	@user =User.find params[:id]
  	@user.delete
  	redirect_to root_path
  end

  def show
  	@user=User.find params[:id]
    
  end
  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_link.html.erb
<%= link_to "Home", root_path %>
<% if logged_in?%>

<%= link_to "Add Product", new_product_path%>
<%= link_to "Profile", user_path(@current_user)%>
<%= link_to "Logout", logout_path%>
<%else%>
<%= link_to "New User", new_user_path%>

<%= link_to "Login", login_path %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jun5Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/link" %>
	<div>
	<% flash.each do |msg_type, msg|%>
	<%=msg%>
	<%end%>
</div>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<% @product.each do |p|%>
<%= p.name%>
<%= p.brand%>
<%= p.price%><br>
<%end%>

app/views/products/new.html.erb
<h1>Products#new</h1>

<%= form_for @product do |p|%>
<%= p.label :name%>
<%= p.text_field :name%><br>

<%= p.label :brand%>
<%= p.text_field :brand%><br>

<%= p.label :price%>
<%= p.text_field :price%><br>

<%= p.submit "Create Product"%><br>
<%end%>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>

<%= form_for @user do |u|%>
<%= u.label :name%>
<%= u.text_field :name%>

<%= u.label :email%>
<%= u.text_field :email%>

<%= u.submit "update"%>
<%end%>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @user.each do |user|%>
<%= user.name%>
<%= user.email%>
<%= link_to "Edit", edit_user_path(user)%>
<%= link_to "Destroy",user, method: :delete, data: {confirm: "sure?"}%><br>

<% end%>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%if @user.errors.any?%>
<% @user.errors.messages.each do |m|%>
<%= m%>
<%end%>
<%end%>

<%= form_for @user do |user|%>
<%=user.label :name %>
<%= user.text_field :name%><br>
<%= user.label :email%>
<%= user.text_field :email%><br>
<%= user.label :password%>
<%= user.text_field :password%><br>
<%= user.submit "Join"%>
<% end %>

<%= %>
<%= %>

app/views/users/show.html.erb
<h1>Users#show</h1>

<%= @user.name%><br>
<%= @user.email%><br>
<%=current_user.products.count%>
<%=link_to "List of Products", products_path%>